# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Biorelated
tagline:          'A weblog'
description:      'A bioinformatics blog'
url:              http://biorelated.com
baseurl:          /

author:
  name:           'George Githinji'
  url:            https://twitter.com/george_l

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/biorelated
